### ISSUE TITLE
请问要如何在作者的example基础上进行修改呢

### ISSUE THREAD

**Issue by LoveUSimone** [zhiyiYo/QMaterialWidgets#10]
作者您好，谢谢您的贡献！
我是pyqt的入门使用者
我想在您的example上进行修改
请问应该怎么做呢

**Comment by zhiyiYo** [comment]
具体是要修改啥？

**Comment by LoveUSimone** [comment]
> 具体是要修改啥？

就是我是想使用你这个设计和板式，然后每个页面的内容估计都要修改！谢谢作者回答了

**Comment by zhiyiYo** [comment]
看下这一期教程：https://www.bilibili.com/video/BV1Uu411j7AV/
目前插件还有点问题，可以用提升为来替换

**Comment by zhiyiYo** [comment]
@LoveUSimone 之前建了一个 PyQt 交流群：295852011，有不懂的欢迎进群一起讨论

**Comment by LoveUSimone** [comment]
> @LoveUSimone 之前建了一个 PyQt 交流群：295852011，有不懂的欢迎进群一起讨论

谢谢，好的
