### ISSUE TITLE
中文 README 中帮助文档链接错误

### ISSUE THREAD

**Issue by muziing** [zhiyiYo/QMaterialWidgets#11]
目前[中文 README](https://github.com/zhiyiYo/QMaterialWidgets/tree/8ff744c9beac0aa4cb88dd38cc9d4fc9e2a832f7/docs/README_zh.md) 中的帮助文档链接为

<https://qmaterilwidgets.readthedocs.io/zh_CN/latest/>

应为

<https://qmaterialwidgets.readthedocs.io/zh_CN/latest/>

**Comment by zhiyiYo** [comment]
感谢指正，新官网地址：https://qmaterialwidgets.vercel.app/zh/
