### ISSUE TITLE
Mac下editable combox组件聚焦后带有MAC系统的聚焦边框

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/QMaterialWidgets#12]
对比fluentwidgets没有，应该是没有加`self.setAttribute(Qt.WA_MacShowFocusRect, False)`属性
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/8281775/f9e2ecd1-4a5d-45a2-8a83-664b1ef766d8)

**Comment by zhiyiYo** [comment]
Mac 下面的字体看起来有点奇怪

**Comment by zhiyiYo** [comment]
但是基类设置过字体了
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/65096819/733805d9-5204-4bd4-b156-4bf687a3927a)

**Comment by zhiyiYo** [comment]
下拉框的祖父类 `LineEditBase` 设置过 `self.setAttribute(Qt.WidgetAttribute.WA_MacShowFocusRect, False)`

**Comment by zhiyiYo** [comment]
应该是 Roboto 字体导致的，可能 mac 上装了此字体

**Comment by zhiyiYo** [comment]
现在还有下拉框焦点和字体问题吗

**Comment by zhiyiYo** [comment]
在 `ComboBox` 的构造函数里面加上 `self.setAttribute(Qt.WidgetAttribute.WA_MacShowFocusRect, False)` 会起作用吗

**Comment by zhiyiYo** [comment]
感谢，0.9.11 会修复这个问题，刚刚发了 0.9.10
