### ISSUE TITLE
Mac下timepicker对话框中的取消和确定按钮间距不对

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/QMaterialWidgets#14]
对比messagebox按钮间距正常
看了下应该是没有添加`setAttribute(Qt.WidgetAttribute.WA_LayoutUsesWidgetRect)`
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/8281775/e4ea10ab-3346-46ed-8157-0255f9d9d7da)

**Comment by zhiyiYo** [comment]
在 `message_box.py` 的第 53 行应该加过这个标志位
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/65096819/67d1f42d-4cfa-4eaf-be1b-c95d6419fc5b)
了

**Comment by zhiyiYo** [comment]
哦哦，给记混了

**Comment by zhiyiYo** [comment]
现在还有这个问题吗

**Comment by zhiyiYo** [comment]
这两个间距好像本来就是 0😂
