### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by longlin10086** [zhiyiYo/QMaterialWidgets#17]
### 中文文档错误
<img width="394" alt="en_doc" src="https://github.com/zhiyiYo/QMaterialWidgets/assets/110278150/f30b84d0-57fe-4df2-9d23-60cc69ee714a">

<img width="411" alt="cn_doc_error" src="https://github.com/zhiyiYo/QMaterialWidgets/assets/110278150/8b1c999f-1f3d-452c-86e6-e05cc3335db1">

中文文档中Warning部分后一个 PyQt-Material-Widgets 应被替换成 PySide6-Material-Widgets

**Comment by zhiyiYo** [comment]
readthedoc 的文档已经不再维护，新的文档为 https://qmaterialwidgets.vercel.app/zh/pages/install
