### ISSUE TITLE
Mac下菜单阴影显示异常

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/QMaterialWidgets#2]
所有涉及菜单显示的地方阴影显示异常：
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/8281775/dd1c91ca-5f50-4765-9259-8cff849d5fc0)

**Comment by zhiyiYo** [comment]
flyout 和 teachingtip 会这样吗

**Comment by zhiyiYo** [comment]
怀疑是 pyside 问题，这几个类和 qfluentwidgets 很像，仅仅是调整了样式

**Comment by zhiyiYo** [comment]
`PopupTeachingTip` 也有阴影吗

**Comment by zhiyiYo** [comment]
可能是 `Qt.Popup` 标志位的锅

**Comment by zhiyiYo** [comment]
如果在 menu.qss 中加上 `RoundMenu {background: transparent}` 之后重新编译，可以起作用吗

**Comment by zhiyiYo** [comment]
ok
