### ISSUE TITLE
Outlined line edits控件中光标未聚焦时底部边框的宽度应该是1px

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/QMaterialWidgets#3]
目前光标未聚焦时，左、上、右都是1px，下边框是0.5px，看起来比较奇怪
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/8281775/9d6bf7b1-91bb-400e-b043-a4d54faacd16)

**Comment by zhiyiYo** [comment]
有些时候会是 1px，就很奇怪

**Comment by zhiyiYo** [comment]
拉伸窗口试试

**Comment by zhiyiYo** [comment]
可能得调整一下绘制的 rect 了

**Comment by zhiyiYo** [comment]
话说mac可以用pyside6插件吗

**Comment by zhiyiYo** [comment]
mac上可以拿到报错信息吗

**Comment by zhiyiYo** [comment]
还真是，但是我之前没写view_plugin的时候也经常启动不了，怀疑是环境导致的，新的环境不会这样

**Comment by zhiyiYo** [comment]
应该改成 CardWidgetPlugin

**Comment by zhiyiYo** [comment]
补全错了

**Comment by zhiyiYo** [comment]
看到 v2ex 上的帖子：https://fast.v2ex.com/t/959000

**Comment by zhiyiYo** [comment]
可能是下面注册的哪个组件有问题

**Comment by zhiyiYo** [comment]
还是不太稳定，第一期可以启动，第二次就又gg了

**Comment by zhiyiYo** [comment]
要是试试把 `Lib\site-packages\PySide6\plugins\designer` 里面的 `qwebengineview.dll` 删除掉

**Comment by zhiyiYo** [comment]
虚拟环境的第三方包里面没有 PySide6 文件夹吗

**Comment by zhiyiYo** [comment]
好吧

**Comment by zhiyiYo** [comment]
不确定是自己组件库的问题还是pyside6的问题

**Comment by zhiyiYo** [comment]
目前已修复底部边框问题

**Comment by zhiyiYo** [comment]
@qianye216 有收到新版本的邮件吗？
