### ISSUE TITLE
时间选择器的 分 输入没有做限制

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/QMaterialWidgets#4]
~~先来一句大佬牛逼，又一个库~~
时间选择器的 分 输入没有做限制，导致可以输入大于59分的时间。
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/14865236/c1a4776d-d350-4918-bcb5-bc770d3de8a5)

**Comment by zhiyiYo** [comment]
加了 validator，但还是限制不了，打算直接搞成 readonly 了

**Comment by Cheukfung** [comment]
暴力检测text change，不符合的输入直接修改为00分可以不

**Comment by zhiyiYo** [comment]
目前的做法是输入非法的数字不改变 time 的值

**Comment by Cheukfung** [comment]
我的建议是如果输入了非法数字，就强制撤销。比如输入了 9 ，则正常显示，如果再输入一个数字变成大于59分的数字 9x，就进行撤销操作变回输入前的9。

**Comment by wb-0624** [comment]
自带的 QIntValidator，无法严格限制 LineEdit 的输入。如果想要严格限制的话，使用 QSpinBox 添加 validator 可以，或者干脆用正则算了。
我自己也遇到这个方面的问题，还有一种就是输入失去焦点时，检测 hasAcceptInput(), 超出范围就设为最大值或者最小值。

**Comment by zhiyiYo** [comment]
回去试试正则表达式

**Comment by zhiyiYo** [comment]
已修复此问题
