### ISSUE TITLE
Windows平台下运行 python ./tools/designer.py，QT designer插件好像加载不出来

### ISSUE THREAD

**Issue by Unreal-abc** [zhiyiYo/QMaterialWidgets#6]
python3.10
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/85796344/b2e56e7f-3df6-47e6-bd58-da46d9a9cb97)

![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/85796344/85db7098-6662-4cdf-b3d5-99dc9debbc07)
![image](https://github.com/zhiyiYo/QMaterialWidgets/assets/85796344/f4aadf2c-a5d0-4fc7-b98f-47e119fe94cc)

**Comment by zhiyiYo** [comment]
pyside6 插件有点问题，见 #3

**Comment by zhiyiYo** [comment]
换成 pyqt5
